config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :videos do
    resources :comments
  end

  root 'videos#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :video
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :content, ContentUploader

  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.video = Video.find(params[:video_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.video, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :video_id, :body)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @comment = Comment.new
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :video_id

  .form-actions
    = f.button :submit

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th User
    %th Video
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.user_id
      %td= comment.video_id
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b User:
  = @comment.user_id
%p
  %b Video:
  = @comment.video_id

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoConverter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
    <%= link_to "Sign out", destroy_user_session_path,method: :delete  %>
<% else %>
    <%= link_to "Login", new_user_session_path %>
    or
    <%= link_to "Register", new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/videos/_form.html.haml
= simple_form_for(@video) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content

  .form-actions
    = f.button :submit

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td= video.content
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

- if @video.processed
  %video{controls: true}
    %source{src: @video.content_url}
- else
  %p#notice
    The video is currently being processed...

%ul
  - @video.comments.each do |comment|
    %li
      %b
        =comment.user.email
      %br
      = comment.body

- unless current_user
  %div
    = link_to "Login", new_user_session_path
    or
    = link_to "Register", new_user_registration_path
    to leave a comment
- else
  = simple_form_for [@video, @comment] do |f|
    = f.input :body, as: :text, label: false, input_html: { rows: 3 }
    = f.hidden_field :user_id, value: current_user.id
    = f.submit 'Add comment'

= link_to 'Back', videos_path